# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UIView.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_UIView(object):
    def setupUi(self, UIView):
        if not UIView.objectName():
            UIView.setObjectName(u"UIView")
        UIView.resize(561, 251)
        icon = QIcon()
        icon.addFile(u"games.ico", QSize(), QIcon.Normal, QIcon.Off)
        UIView.setWindowIcon(icon)
        self.centralwidget = QWidget(UIView)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 541, 192))
        self.groupBox_2.setStyleSheet(u"border:none")
        self.gridLayout_2 = QGridLayout(self.groupBox_2)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 39, 0, 1)
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")

        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)

        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")

        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)

        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")

        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)

        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")

        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 10, 16, 192))
        self.groupBox_3.setStyleSheet(u"border:none")
        self.gridLayout_3 = QGridLayout(self.groupBox_3)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 39, 0, 1)
        self.label_19 = QLabel(self.groupBox_3)
        self.label_19.setObjectName(u"label_19")

        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)

        self.label_21 = QLabel(self.groupBox_3)
        self.label_21.setObjectName(u"label_21")

        self.gridLayout_3.addWidget(self.label_21, 3, 0, 1, 1)

        self.label_18 = QLabel(self.groupBox_3)
        self.label_18.setObjectName(u"label_18")

        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)

        self.label_20 = QLabel(self.groupBox_3)
        self.label_20.setObjectName(u"label_20")

        self.gridLayout_3.addWidget(self.label_20, 2, 0, 1, 1)

        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 10, 541, 231))
        self.groupBox_4.setStyleSheet(u"#groupBox_4 {border:none}")
        self.verticalLayout = QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.groupBox = QGroupBox(self.groupBox_4)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setStyleSheet(u"")
        self.groupBox.setAlignment(Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.gridLayout = QGridLayout(self.groupBox)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QSize(79, 38))
        font = QFont()
        font.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1, Qt.AlignHCenter|Qt.AlignVCenter)

        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy1)
        self.label_6.setMinimumSize(QSize(103, 0))
        self.label_6.setSizeIncrement(QSize(0, 0))
        font1 = QFont()
        font1.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font1.setBold(True)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setWeight(75)
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)

        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        sizePolicy1.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy1)
        self.label_7.setMinimumSize(QSize(49, 0))
        self.label_7.setFont(font1)
        self.label_7.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)

        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        sizePolicy1.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy1)
        self.label_8.setMinimumSize(QSize(103, 0))
        self.label_8.setSizeIncrement(QSize(0, 0))
        self.label_8.setFont(font1)
        self.label_8.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)

        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        sizePolicy1.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy1)
        self.label_9.setMinimumSize(QSize(78, 0))
        self.label_9.setFont(font1)
        self.label_9.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_9, 0, 4, 1, 1)

        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        sizePolicy1.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy1)
        self.label_10.setMinimumSize(QSize(78, 0))
        self.label_10.setFont(font1)
        self.label_10.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_10, 0, 5, 1, 1)

        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        sizePolicy1.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy1)
        self.label_11.setMinimumSize(QSize(49, 0))
        self.label_11.setFont(font1)
        self.label_11.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_11, 0, 6, 1, 1)

        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy2)
        self.label.setMinimumSize(QSize(55, 38))
        font2 = QFont()
        font2.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font2.setBold(True)
        font2.setWeight(75)
        self.label.setFont(font2)
        self.label.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label, 1, 0, 1, 1, Qt.AlignHCenter)

        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy3)
        font3 = QFont()
        font3.setBold(True)
        font3.setWeight(75)
        self.pushButton.setFont(font3)
        self.pushButton.setFocusPolicy(Qt.NoFocus)
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)

        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1, Qt.AlignHCenter)

        self.pushButton_5 = QPushButton(self.groupBox)
        self.pushButton_5.setObjectName(u"pushButton_5")
        sizePolicy3.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy3)
        self.pushButton_5.setFocusPolicy(Qt.NoFocus)
        self.pushButton_5.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_5, 1, 2, 1, 1, Qt.AlignHCenter)

        self.doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        sizePolicy3.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy3)
        self.doubleSpinBox.setFocusPolicy(Qt.NoFocus)
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.doubleSpinBox.setMinimum(-1.000000000000000)
        self.doubleSpinBox.setMaximum(1.000000000000000)
        self.doubleSpinBox.setSingleStep(0.050000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox, 1, 4, 1, 1, Qt.AlignHCenter)

        self.doubleSpinBox_5 = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_5.setObjectName(u"doubleSpinBox_5")
        sizePolicy3.setHeightForWidth(self.doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_5.setSizePolicy(sizePolicy3)
        self.doubleSpinBox_5.setFocusPolicy(Qt.NoFocus)
        self.doubleSpinBox_5.setMinimum(-1.000000000000000)
        self.doubleSpinBox_5.setMaximum(1.000000000000000)
        self.doubleSpinBox_5.setSingleStep(0.050000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox_5, 1, 5, 1, 1, Qt.AlignHCenter)

        self.pushButton_13 = QPushButton(self.groupBox)
        self.pushButton_13.setObjectName(u"pushButton_13")
        sizePolicy3.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy3)
        self.pushButton_13.setFocusPolicy(Qt.NoFocus)
        self.pushButton_13.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_13, 1, 6, 1, 1, Qt.AlignHCenter)

        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        sizePolicy2.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy2)
        self.label_3.setMinimumSize(QSize(55, 38))
        self.label_3.setFont(font2)
        self.label_3.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1, Qt.AlignHCenter)

        self.pushButton_2 = QPushButton(self.groupBox)
        self.pushButton_2.setObjectName(u"pushButton_2")
        sizePolicy3.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy3)
        self.pushButton_2.setFont(font3)
        self.pushButton_2.setFocusPolicy(Qt.NoFocus)
        self.pushButton_2.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1, Qt.AlignHCenter)

        self.pushButton_6 = QPushButton(self.groupBox)
        self.pushButton_6.setObjectName(u"pushButton_6")
        sizePolicy3.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy3)
        self.pushButton_6.setFocusPolicy(Qt.NoFocus)
        self.pushButton_6.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1, Qt.AlignHCenter)

        self.pushButton_10 = QPushButton(self.groupBox)
        self.pushButton_10.setObjectName(u"pushButton_10")
        sizePolicy3.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy3)
        self.pushButton_10.setFont(font3)
        self.pushButton_10.setFocusPolicy(Qt.NoFocus)
        self.pushButton_10.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_10, 2, 3, 1, 1, Qt.AlignHCenter)

        self.doubleSpinBox_2 = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        sizePolicy3.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy3)
        self.doubleSpinBox_2.setFocusPolicy(Qt.NoFocus)
        self.doubleSpinBox_2.setMinimum(-1.000000000000000)
        self.doubleSpinBox_2.setMaximum(1.000000000000000)
        self.doubleSpinBox_2.setSingleStep(0.050000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox_2, 2, 4, 1, 1, Qt.AlignHCenter)

        self.doubleSpinBox_6 = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_6.setObjectName(u"doubleSpinBox_6")
        sizePolicy3.setHeightForWidth(self.doubleSpinBox_6.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_6.setSizePolicy(sizePolicy3)
        self.doubleSpinBox_6.setFocusPolicy(Qt.NoFocus)
        self.doubleSpinBox_6.setMinimum(-1.000000000000000)
        self.doubleSpinBox_6.setMaximum(1.000000000000000)
        self.doubleSpinBox_6.setSingleStep(0.050000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox_6, 2, 5, 1, 1, Qt.AlignHCenter)

        self.pushButton_14 = QPushButton(self.groupBox)
        self.pushButton_14.setObjectName(u"pushButton_14")
        sizePolicy3.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy3)
        self.pushButton_14.setFocusPolicy(Qt.NoFocus)
        self.pushButton_14.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_14, 2, 6, 1, 1, Qt.AlignHCenter)

        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        sizePolicy2.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy2)
        self.label_2.setMinimumSize(QSize(55, 38))
        self.label_2.setFont(font2)
        self.label_2.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1, Qt.AlignHCenter)

        self.pushButton_3 = QPushButton(self.groupBox)
        self.pushButton_3.setObjectName(u"pushButton_3")
        sizePolicy3.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy3)
        self.pushButton_3.setFont(font3)
        self.pushButton_3.setFocusPolicy(Qt.NoFocus)
        self.pushButton_3.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_3, 3, 1, 1, 1, Qt.AlignHCenter)

        self.pushButton_7 = QPushButton(self.groupBox)
        self.pushButton_7.setObjectName(u"pushButton_7")
        sizePolicy3.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy3)
        self.pushButton_7.setFocusPolicy(Qt.NoFocus)
        self.pushButton_7.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_7, 3, 2, 1, 1, Qt.AlignHCenter)

        self.pushButton_11 = QPushButton(self.groupBox)
        self.pushButton_11.setObjectName(u"pushButton_11")
        sizePolicy3.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy3)
        self.pushButton_11.setFont(font3)
        self.pushButton_11.setFocusPolicy(Qt.NoFocus)
        self.pushButton_11.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_11, 3, 3, 1, 1, Qt.AlignHCenter)

        self.doubleSpinBox_3 = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_3.setObjectName(u"doubleSpinBox_3")
        sizePolicy3.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy3)
        self.doubleSpinBox_3.setFocusPolicy(Qt.NoFocus)
        self.doubleSpinBox_3.setMinimum(-1.000000000000000)
        self.doubleSpinBox_3.setMaximum(1.000000000000000)
        self.doubleSpinBox_3.setSingleStep(0.050000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox_3, 3, 4, 1, 1, Qt.AlignHCenter)

        self.doubleSpinBox_7 = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_7.setObjectName(u"doubleSpinBox_7")
        sizePolicy3.setHeightForWidth(self.doubleSpinBox_7.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_7.setSizePolicy(sizePolicy3)
        self.doubleSpinBox_7.setFocusPolicy(Qt.NoFocus)
        self.doubleSpinBox_7.setMinimum(-1.000000000000000)
        self.doubleSpinBox_7.setMaximum(1.000000000000000)
        self.doubleSpinBox_7.setSingleStep(0.050000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox_7, 3, 5, 1, 1, Qt.AlignHCenter)

        self.pushButton_15 = QPushButton(self.groupBox)
        self.pushButton_15.setObjectName(u"pushButton_15")
        sizePolicy3.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy3)
        self.pushButton_15.setFocusPolicy(Qt.NoFocus)
        self.pushButton_15.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_15, 3, 6, 1, 1, Qt.AlignHCenter)

        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        sizePolicy2.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy2)
        self.label_4.setMinimumSize(QSize(55, 38))
        self.label_4.setFont(font2)
        self.label_4.setAlignment(Qt.AlignCenter)

        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1, Qt.AlignHCenter)

        self.pushButton_4 = QPushButton(self.groupBox)
        self.pushButton_4.setObjectName(u"pushButton_4")
        sizePolicy3.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy3)
        self.pushButton_4.setFont(font3)
        self.pushButton_4.setFocusPolicy(Qt.NoFocus)
        self.pushButton_4.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_4, 4, 1, 1, 1, Qt.AlignHCenter)

        self.pushButton_8 = QPushButton(self.groupBox)
        self.pushButton_8.setObjectName(u"pushButton_8")
        sizePolicy3.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy3)
        self.pushButton_8.setFocusPolicy(Qt.NoFocus)
        self.pushButton_8.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_8, 4, 2, 1, 1, Qt.AlignHCenter)

        self.pushButton_12 = QPushButton(self.groupBox)
        self.pushButton_12.setObjectName(u"pushButton_12")
        sizePolicy3.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy3)
        self.pushButton_12.setFont(font3)
        self.pushButton_12.setFocusPolicy(Qt.NoFocus)
        self.pushButton_12.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_12, 4, 3, 1, 1, Qt.AlignHCenter)

        self.doubleSpinBox_4 = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_4.setObjectName(u"doubleSpinBox_4")
        sizePolicy3.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy3)
        self.doubleSpinBox_4.setFocusPolicy(Qt.NoFocus)
        self.doubleSpinBox_4.setMinimum(-1.000000000000000)
        self.doubleSpinBox_4.setMaximum(1.000000000000000)
        self.doubleSpinBox_4.setSingleStep(0.050000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox_4, 4, 4, 1, 1, Qt.AlignHCenter)

        self.doubleSpinBox_8 = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_8.setObjectName(u"doubleSpinBox_8")
        sizePolicy3.setHeightForWidth(self.doubleSpinBox_8.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_8.setSizePolicy(sizePolicy3)
        self.doubleSpinBox_8.setFocusPolicy(Qt.NoFocus)
        self.doubleSpinBox_8.setMinimum(-1.000000000000000)
        self.doubleSpinBox_8.setMaximum(1.000000000000000)
        self.doubleSpinBox_8.setSingleStep(0.050000000000000)

        self.gridLayout.addWidget(self.doubleSpinBox_8, 4, 5, 1, 1, Qt.AlignHCenter)

        self.pushButton_16 = QPushButton(self.groupBox)
        self.pushButton_16.setObjectName(u"pushButton_16")
        sizePolicy3.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy3)
        self.pushButton_16.setFocusPolicy(Qt.NoFocus)
        self.pushButton_16.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_16, 4, 6, 1, 1, Qt.AlignHCenter)

        self.pushButton_9 = QPushButton(self.groupBox)
        self.pushButton_9.setObjectName(u"pushButton_9")
        sizePolicy3.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy3)
        self.pushButton_9.setFont(font3)
        self.pushButton_9.setFocusPolicy(Qt.NoFocus)
        self.pushButton_9.setCheckable(True)

        self.gridLayout.addWidget(self.pushButton_9, 1, 3, 1, 1, Qt.AlignHCenter)


        self.verticalLayout.addWidget(self.groupBox)

        self.groupBox_5 = QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(u"groupBox_5")
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy4)
        self.horizontalLayout = QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_16 = QLabel(self.groupBox_5)
        self.label_16.setObjectName(u"label_16")
        sizePolicy2.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy2)
        self.label_16.setMinimumSize(QSize(79, 37))
        self.label_16.setFont(font2)
        self.label_16.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.label_16)

        self.pushButton_17 = QPushButton(self.groupBox_5)
        self.pushButton_17.setObjectName(u"pushButton_17")
        sizePolicy3.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy3)
        self.pushButton_17.setFocusPolicy(Qt.NoFocus)
        self.pushButton_17.setCheckable(True)

        self.horizontalLayout.addWidget(self.pushButton_17)

        self.label_17 = QLabel(self.groupBox_5)
        self.label_17.setObjectName(u"label_17")
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QSize(419, 37))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.label_17.setFont(font4)
        self.label_17.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout.addWidget(self.label_17)


        self.verticalLayout.addWidget(self.groupBox_5)

        UIView.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.pushButton, self.pushButton_5)
        QWidget.setTabOrder(self.pushButton_5, self.doubleSpinBox)
        QWidget.setTabOrder(self.doubleSpinBox, self.doubleSpinBox_5)
        QWidget.setTabOrder(self.doubleSpinBox_5, self.pushButton_13)
        QWidget.setTabOrder(self.pushButton_13, self.pushButton_2)
        QWidget.setTabOrder(self.pushButton_2, self.pushButton_6)
        QWidget.setTabOrder(self.pushButton_6, self.pushButton_10)
        QWidget.setTabOrder(self.pushButton_10, self.doubleSpinBox_2)
        QWidget.setTabOrder(self.doubleSpinBox_2, self.doubleSpinBox_6)
        QWidget.setTabOrder(self.doubleSpinBox_6, self.pushButton_14)
        QWidget.setTabOrder(self.pushButton_14, self.pushButton_3)
        QWidget.setTabOrder(self.pushButton_3, self.pushButton_7)
        QWidget.setTabOrder(self.pushButton_7, self.pushButton_11)
        QWidget.setTabOrder(self.pushButton_11, self.doubleSpinBox_3)
        QWidget.setTabOrder(self.doubleSpinBox_3, self.doubleSpinBox_7)
        QWidget.setTabOrder(self.doubleSpinBox_7, self.pushButton_15)
        QWidget.setTabOrder(self.pushButton_15, self.pushButton_4)
        QWidget.setTabOrder(self.pushButton_4, self.pushButton_8)
        QWidget.setTabOrder(self.pushButton_8, self.pushButton_12)
        QWidget.setTabOrder(self.pushButton_12, self.doubleSpinBox_4)
        QWidget.setTabOrder(self.doubleSpinBox_4, self.doubleSpinBox_8)
        QWidget.setTabOrder(self.doubleSpinBox_8, self.pushButton_16)

        self.retranslateUi(UIView)

        QMetaObject.connectSlotsByName(UIView)
    # setupUi

    def retranslateUi(self, UIView):
        UIView.setWindowTitle(QCoreApplication.translate("UIView", u"OC2TAS", None))
        self.groupBox_2.setTitle("")
        self.label_13.setText("")
        self.label_15.setText("")
        self.label_12.setText("")
        self.label_14.setText("")
        self.groupBox_3.setTitle("")
        self.label_19.setText("")
        self.label_21.setText("")
        self.label_18.setText("")
        self.label_20.setText("")
        self.groupBox_4.setTitle("")
        self.groupBox.setTitle("")
        self.label_5.setText("")
        self.label_6.setText(QCoreApplication.translate("UIView", u"PICKUP", None))
        self.label_7.setText(QCoreApplication.translate("UIView", u"USE", None))
        self.label_8.setText(QCoreApplication.translate("UIView", u"DASH", None))
        self.label_9.setText(QCoreApplication.translate("UIView", u"X", None))
        self.label_10.setText(QCoreApplication.translate("UIView", u"Y", None))
        self.label_11.setText(QCoreApplication.translate("UIView", u"EMO", None))
        self.label.setText(QCoreApplication.translate("UIView", u"P1", None))
        self.pushButton.setText(QCoreApplication.translate("UIView", u"00000", None))
        self.pushButton_5.setText("")
        self.pushButton_13.setText("")
        self.label_3.setText(QCoreApplication.translate("UIView", u"P2", None))
        self.pushButton_2.setText(QCoreApplication.translate("UIView", u"00000", None))
        self.pushButton_6.setText("")
        self.pushButton_10.setText(QCoreApplication.translate("UIView", u"00000", None))
        self.pushButton_14.setText("")
        self.label_2.setText(QCoreApplication.translate("UIView", u"P3", None))
        self.pushButton_3.setText(QCoreApplication.translate("UIView", u"00000", None))
        self.pushButton_7.setText("")
        self.pushButton_11.setText(QCoreApplication.translate("UIView", u"00000", None))
        self.pushButton_15.setText("")
        self.label_4.setText(QCoreApplication.translate("UIView", u"P4", None))
        self.pushButton_4.setText(QCoreApplication.translate("UIView", u"00000", None))
        self.pushButton_8.setText("")
        self.pushButton_12.setText(QCoreApplication.translate("UIView", u"00000", None))
        self.pushButton_16.setText("")
        self.pushButton_9.setText(QCoreApplication.translate("UIView", u"00000", None))
        self.groupBox_5.setTitle("")
        self.label_16.setText(QCoreApplication.translate("UIView", u"SHIFT", None))
        self.pushButton_17.setText("")
        self.label_17.setText(QCoreApplication.translate("UIView", u"FRAME 00000 ", None))
    # retranslateUi

